import AddTodo from "@/components/AddTodo";
import TodoList from "@/components/TodoList";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Тодошка</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        <h1 className="app-title">Мой список:</h1>
        <AddTodo />
        <TodoList />
      </div>
    </>
  );
}
